### ISSUE TITLE
CR: Deployment with passenger

### ISSUE THREAD

**Issue by jeredepp** [panter/catladder#2]
After deploying the application to a passenger instance, we need to execute `sudo /etc/init.d/nginx restart` to restart the node app.

- Deploy magic catladder
- sudo /etc/init.d/nginx restart

**Comment by macrozone** [comment]
should we make this configurable?

**Comment by jeredepp** [comment]
Would be nice to do something like `catladder deploy staging --min-instances=1 --max-instances=3` but let's first accumulate some knowledge about [the passenger](https://www.youtube.com/watch?v=S0nlygb1Qfw)
